# Generated by Django 4.1 on 2022-10-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tex_data',
            new_name='tax_data',
        ),
    ]
